pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot-preview[bot]
      - "status-success=codecov/project"
      - "status-success=ci/circleci: build"
    actions:
      merge:
        method: merge
