pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
      - status-success=ci/circleci: build
      - status-success=codecov/project
    actions:
      merge:
        method: merge
